package de.fhdo.terminologie.ws.search;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2015-05-13T09:53:17.052+02:00
 * Generated source version: 3.0.3
 * 
 */
@WebService(targetNamespace = "http://search.ws.terminologie.fhdo.de/", name = "Search")
@XmlSeeAlso({ObjectFactory.class, types.termserver.fhdo.de.ObjectFactory.class})
public interface Search {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://search.ws.terminologie.fhdo.de/Search/ReturnCodeSystemDetailsRequest", output = "http://search.ws.terminologie.fhdo.de/Search/ReturnCodeSystemDetailsResponse")
    @RequestWrapper(localName = "ReturnCodeSystemDetails", targetNamespace = "http://search.ws.terminologie.fhdo.de/", className = "de.fhdo.terminologie.ws.search.ReturnCodeSystemDetails")
    @WebMethod(operationName = "ReturnCodeSystemDetails")
    @ResponseWrapper(localName = "ReturnCodeSystemDetailsResponse", targetNamespace = "http://search.ws.terminologie.fhdo.de/", className = "de.fhdo.terminologie.ws.search.ReturnCodeSystemDetailsResponse")
    public de.fhdo.terminologie.ws.search.ReturnCodeSystemDetailsResponse.Return returnCodeSystemDetails(
        @WebParam(name = "parameter", targetNamespace = "")
        de.fhdo.terminologie.ws.search.ReturnCodeSystemDetailsRequestType parameter
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://search.ws.terminologie.fhdo.de/Search/ListMetadataParameterRequest", output = "http://search.ws.terminologie.fhdo.de/Search/ListMetadataParameterResponse")
    @RequestWrapper(localName = "ListMetadataParameter", targetNamespace = "http://search.ws.terminologie.fhdo.de/", className = "de.fhdo.terminologie.ws.search.ListMetadataParameter")
    @WebMethod(operationName = "ListMetadataParameter")
    @ResponseWrapper(localName = "ListMetadataParameterResponse", targetNamespace = "http://search.ws.terminologie.fhdo.de/", className = "de.fhdo.terminologie.ws.search.ListMetadataParameterResponse")
    public de.fhdo.terminologie.ws.search.ListMetadataParameterResponse.Return listMetadataParameter(
        @WebParam(name = "parameter", targetNamespace = "")
        de.fhdo.terminologie.ws.search.ListMetadataParameterRequestType parameter
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://search.ws.terminologie.fhdo.de/Search/ListConceptAssociationTypesRequest", output = "http://search.ws.terminologie.fhdo.de/Search/ListConceptAssociationTypesResponse")
    @RequestWrapper(localName = "ListConceptAssociationTypes", targetNamespace = "http://search.ws.terminologie.fhdo.de/", className = "de.fhdo.terminologie.ws.search.ListConceptAssociationTypes")
    @WebMethod(operationName = "ListConceptAssociationTypes")
    @ResponseWrapper(localName = "ListConceptAssociationTypesResponse", targetNamespace = "http://search.ws.terminologie.fhdo.de/", className = "de.fhdo.terminologie.ws.search.ListConceptAssociationTypesResponse")
    public de.fhdo.terminologie.ws.search.ListConceptAssociationTypesResponse.Return listConceptAssociationTypes(
        @WebParam(name = "parameter", targetNamespace = "")
        de.fhdo.terminologie.ws.search.ListConceptAssociationTypesRequestType parameter
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://search.ws.terminologie.fhdo.de/Search/ListGloballySearchedConceptsRequest", output = "http://search.ws.terminologie.fhdo.de/Search/ListGloballySearchedConceptsResponse")
    @RequestWrapper(localName = "ListGloballySearchedConcepts", targetNamespace = "http://search.ws.terminologie.fhdo.de/", className = "de.fhdo.terminologie.ws.search.ListGloballySearchedConcepts")
    @WebMethod(operationName = "ListGloballySearchedConcepts")
    @ResponseWrapper(localName = "ListGloballySearchedConceptsResponse", targetNamespace = "http://search.ws.terminologie.fhdo.de/", className = "de.fhdo.terminologie.ws.search.ListGloballySearchedConceptsResponse")
    public de.fhdo.terminologie.ws.search.ListGloballySearchedConceptsResponse.Return listGloballySearchedConcepts(
        @WebParam(name = "parameter", targetNamespace = "")
        de.fhdo.terminologie.ws.search.ListGloballySearchedConceptsRequestType parameter
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://search.ws.terminologie.fhdo.de/Search/ReturnValueSetConceptMetadataRequest", output = "http://search.ws.terminologie.fhdo.de/Search/ReturnValueSetConceptMetadataResponse")
    @RequestWrapper(localName = "ReturnValueSetConceptMetadata", targetNamespace = "http://search.ws.terminologie.fhdo.de/", className = "de.fhdo.terminologie.ws.search.ReturnValueSetConceptMetadata")
    @WebMethod(operationName = "ReturnValueSetConceptMetadata")
    @ResponseWrapper(localName = "ReturnValueSetConceptMetadataResponse", targetNamespace = "http://search.ws.terminologie.fhdo.de/", className = "de.fhdo.terminologie.ws.search.ReturnValueSetConceptMetadataResponse")
    public de.fhdo.terminologie.ws.search.ReturnValueSetConceptMetadataResponse.Return returnValueSetConceptMetadata(
        @WebParam(name = "parameter", targetNamespace = "")
        de.fhdo.terminologie.ws.search.ReturnValueSetConceptMetadataRequestType parameter
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://search.ws.terminologie.fhdo.de/Search/ReturnConceptAssociationTypeDetailsRequest", output = "http://search.ws.terminologie.fhdo.de/Search/ReturnConceptAssociationTypeDetailsResponse")
    @RequestWrapper(localName = "ReturnConceptAssociationTypeDetails", targetNamespace = "http://search.ws.terminologie.fhdo.de/", className = "de.fhdo.terminologie.ws.search.ReturnConceptAssociationTypeDetails")
    @WebMethod(operationName = "ReturnConceptAssociationTypeDetails")
    @ResponseWrapper(localName = "ReturnConceptAssociationTypeDetailsResponse", targetNamespace = "http://search.ws.terminologie.fhdo.de/", className = "de.fhdo.terminologie.ws.search.ReturnConceptAssociationTypeDetailsResponse")
    public de.fhdo.terminologie.ws.search.ReturnConceptAssociationTypeDetailsResponse.Return returnConceptAssociationTypeDetails(
        @WebParam(name = "parameter", targetNamespace = "")
        de.fhdo.terminologie.ws.search.ReturnConceptAssociationTypeDetailsRequestType parameter
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://search.ws.terminologie.fhdo.de/Search/ListValueSetContentsRequest", output = "http://search.ws.terminologie.fhdo.de/Search/ListValueSetContentsResponse")
    @RequestWrapper(localName = "ListValueSetContents", targetNamespace = "http://search.ws.terminologie.fhdo.de/", className = "de.fhdo.terminologie.ws.search.ListValueSetContents")
    @WebMethod(operationName = "ListValueSetContents")
    @ResponseWrapper(localName = "ListValueSetContentsResponse", targetNamespace = "http://search.ws.terminologie.fhdo.de/", className = "de.fhdo.terminologie.ws.search.ListValueSetContentsResponse")
    public de.fhdo.terminologie.ws.search.ListValueSetContentsResponse.Return listValueSetContents(
        @WebParam(name = "parameter", targetNamespace = "")
        de.fhdo.terminologie.ws.search.ListValueSetContentsRequestType parameter
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://search.ws.terminologie.fhdo.de/Search/ListCodeSystemsInTaxonomyRequest", output = "http://search.ws.terminologie.fhdo.de/Search/ListCodeSystemsInTaxonomyResponse")
    @RequestWrapper(localName = "ListCodeSystemsInTaxonomy", targetNamespace = "http://search.ws.terminologie.fhdo.de/", className = "de.fhdo.terminologie.ws.search.ListCodeSystemsInTaxonomy")
    @WebMethod(operationName = "ListCodeSystemsInTaxonomy")
    @ResponseWrapper(localName = "ListCodeSystemsInTaxonomyResponse", targetNamespace = "http://search.ws.terminologie.fhdo.de/", className = "de.fhdo.terminologie.ws.search.ListCodeSystemsInTaxonomyResponse")
    public de.fhdo.terminologie.ws.search.ListCodeSystemsInTaxonomyResponse.Return listCodeSystemsInTaxonomy(
        @WebParam(name = "parameter", targetNamespace = "")
        de.fhdo.terminologie.ws.search.ListCodeSystemsInTaxonomyRequestType parameter
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://search.ws.terminologie.fhdo.de/Search/ReturnConceptValueSetMembershipRequest", output = "http://search.ws.terminologie.fhdo.de/Search/ReturnConceptValueSetMembershipResponse")
    @RequestWrapper(localName = "ReturnConceptValueSetMembership", targetNamespace = "http://search.ws.terminologie.fhdo.de/", className = "de.fhdo.terminologie.ws.search.ReturnConceptValueSetMembership")
    @WebMethod(operationName = "ReturnConceptValueSetMembership")
    @ResponseWrapper(localName = "ReturnConceptValueSetMembershipResponse", targetNamespace = "http://search.ws.terminologie.fhdo.de/", className = "de.fhdo.terminologie.ws.search.ReturnConceptValueSetMembershipResponse")
    public de.fhdo.terminologie.ws.search.ReturnConceptValueSetMembershipResponse.Return returnConceptValueSetMembership(
        @WebParam(name = "parameter", targetNamespace = "")
        de.fhdo.terminologie.ws.search.ReturnConceptValueSetMembershipRequestType parameter
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://search.ws.terminologie.fhdo.de/Search/ListDomainsRequest", output = "http://search.ws.terminologie.fhdo.de/Search/ListDomainsResponse")
    @RequestWrapper(localName = "ListDomains", targetNamespace = "http://search.ws.terminologie.fhdo.de/", className = "de.fhdo.terminologie.ws.search.ListDomains")
    @WebMethod(operationName = "ListDomains")
    @ResponseWrapper(localName = "ListDomainsResponse", targetNamespace = "http://search.ws.terminologie.fhdo.de/", className = "de.fhdo.terminologie.ws.search.ListDomainsResponse")
    public de.fhdo.terminologie.ws.search.ListDomainsResponse.Return listDomains(
        @WebParam(name = "parameter", targetNamespace = "")
        de.fhdo.terminologie.ws.search.ListDomainsRequestType parameter
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://search.ws.terminologie.fhdo.de/Search/ListValueSetsRequest", output = "http://search.ws.terminologie.fhdo.de/Search/ListValueSetsResponse")
    @RequestWrapper(localName = "ListValueSets", targetNamespace = "http://search.ws.terminologie.fhdo.de/", className = "de.fhdo.terminologie.ws.search.ListValueSets")
    @WebMethod(operationName = "ListValueSets")
    @ResponseWrapper(localName = "ListValueSetsResponse", targetNamespace = "http://search.ws.terminologie.fhdo.de/", className = "de.fhdo.terminologie.ws.search.ListValueSetsResponse")
    public de.fhdo.terminologie.ws.search.ListValueSetsResponse.Return listValueSets(
        @WebParam(name = "parameter", targetNamespace = "")
        de.fhdo.terminologie.ws.search.ListValueSetsRequestType parameter
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://search.ws.terminologie.fhdo.de/Search/ReturnValueSetDetailsRequest", output = "http://search.ws.terminologie.fhdo.de/Search/ReturnValueSetDetailsResponse")
    @RequestWrapper(localName = "ReturnValueSetDetails", targetNamespace = "http://search.ws.terminologie.fhdo.de/", className = "de.fhdo.terminologie.ws.search.ReturnValueSetDetails")
    @WebMethod(operationName = "ReturnValueSetDetails")
    @ResponseWrapper(localName = "ReturnValueSetDetailsResponse", targetNamespace = "http://search.ws.terminologie.fhdo.de/", className = "de.fhdo.terminologie.ws.search.ReturnValueSetDetailsResponse")
    public de.fhdo.terminologie.ws.search.ReturnValueSetDetailsResponse.Return returnValueSetDetails(
        @WebParam(name = "parameter", targetNamespace = "")
        de.fhdo.terminologie.ws.search.ReturnValueSetDetailsRequestType parameter
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://search.ws.terminologie.fhdo.de/Search/ListCodeSystemsRequest", output = "http://search.ws.terminologie.fhdo.de/Search/ListCodeSystemsResponse")
    @RequestWrapper(localName = "ListCodeSystems", targetNamespace = "http://search.ws.terminologie.fhdo.de/", className = "de.fhdo.terminologie.ws.search.ListCodeSystems")
    @WebMethod(operationName = "ListCodeSystems")
    @ResponseWrapper(localName = "ListCodeSystemsResponse", targetNamespace = "http://search.ws.terminologie.fhdo.de/", className = "de.fhdo.terminologie.ws.search.ListCodeSystemsResponse")
    public de.fhdo.terminologie.ws.search.ListCodeSystemsResponse.Return listCodeSystems(
        @WebParam(name = "parameter", targetNamespace = "")
        de.fhdo.terminologie.ws.search.ListCodeSystemsRequestType parameter
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://search.ws.terminologie.fhdo.de/Search/ListCodeSystemConceptsRequest", output = "http://search.ws.terminologie.fhdo.de/Search/ListCodeSystemConceptsResponse")
    @RequestWrapper(localName = "ListCodeSystemConcepts", targetNamespace = "http://search.ws.terminologie.fhdo.de/", className = "de.fhdo.terminologie.ws.search.ListCodeSystemConcepts")
    @WebMethod(operationName = "ListCodeSystemConcepts")
    @ResponseWrapper(localName = "ListCodeSystemConceptsResponse", targetNamespace = "http://search.ws.terminologie.fhdo.de/", className = "de.fhdo.terminologie.ws.search.ListCodeSystemConceptsResponse")
    public de.fhdo.terminologie.ws.search.ListCodeSystemConceptsResponse.Return listCodeSystemConcepts(
        @WebParam(name = "parameter", targetNamespace = "")
        de.fhdo.terminologie.ws.search.ListCodeSystemConceptsRequestType parameter
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://search.ws.terminologie.fhdo.de/Search/ReturnConceptDetailsRequest", output = "http://search.ws.terminologie.fhdo.de/Search/ReturnConceptDetailsResponse")
    @RequestWrapper(localName = "ReturnConceptDetails", targetNamespace = "http://search.ws.terminologie.fhdo.de/", className = "de.fhdo.terminologie.ws.search.ReturnConceptDetails")
    @WebMethod(operationName = "ReturnConceptDetails")
    @ResponseWrapper(localName = "ReturnConceptDetailsResponse", targetNamespace = "http://search.ws.terminologie.fhdo.de/", className = "de.fhdo.terminologie.ws.search.ReturnConceptDetailsResponse")
    public de.fhdo.terminologie.ws.search.ReturnConceptDetailsResponse.Return returnConceptDetails(
        @WebParam(name = "parameter", targetNamespace = "")
        de.fhdo.terminologie.ws.search.ReturnConceptDetailsRequestType parameter
    );

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://search.ws.terminologie.fhdo.de/Search/GetTermserverVersionRequest", output = "http://search.ws.terminologie.fhdo.de/Search/GetTermserverVersionResponse")
    @RequestWrapper(localName = "GetTermserverVersion", targetNamespace = "http://search.ws.terminologie.fhdo.de/", className = "de.fhdo.terminologie.ws.search.GetTermserverVersion")
    @WebMethod(operationName = "GetTermserverVersion")
    @ResponseWrapper(localName = "GetTermserverVersionResponse", targetNamespace = "http://search.ws.terminologie.fhdo.de/", className = "de.fhdo.terminologie.ws.search.GetTermserverVersionResponse")
    public de.fhdo.terminologie.ws.search.GetTermserverVersionResponse.Return getTermserverVersion();

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://search.ws.terminologie.fhdo.de/Search/ListDomainValuesRequest", output = "http://search.ws.terminologie.fhdo.de/Search/ListDomainValuesResponse")
    @RequestWrapper(localName = "ListDomainValues", targetNamespace = "http://search.ws.terminologie.fhdo.de/", className = "de.fhdo.terminologie.ws.search.ListDomainValues")
    @WebMethod(operationName = "ListDomainValues")
    @ResponseWrapper(localName = "ListDomainValuesResponse", targetNamespace = "http://search.ws.terminologie.fhdo.de/", className = "de.fhdo.terminologie.ws.search.ListDomainValuesResponse")
    public de.fhdo.terminologie.ws.search.ListDomainValuesResponse.Return listDomainValues(
        @WebParam(name = "parameter", targetNamespace = "")
        de.fhdo.terminologie.ws.search.ListDomainValuesRequestType parameter
    );
}
